### ISSUE TITLE
Missing project

### ISSUE THREAD

**Issue by crisszkutnik** [GuidoDipietro/GuidoDipietro#1]
Hi Guido! I was reading your GitHub presentation and I realized that you did not feature some important projects! That do is a shame because most of them are spectacular! I think that [this one](https://github.com/GuidoDipietro/TPAlgoritmos-agosto-2019) is the most important (repo might be private, idk). Other than that, I find your README.md truly magnificent.

Regards, your fellow classmate and friend, Cristobal

**Comment by GuidoDipietro** [comment]
Oh, that project! I purposely left that one out in order to keep the criminality rate low. Due to the excess of `SWAG` (Success With A Glitch) present in the source code, most people would simply go out on the streets, kidnap a random person, and force them to read the code. I did not really like that (I'm not really a braggart, you know), so I just made it private.

Besides, a few users reported `DEATH` (Dang! Empty As The Hollow) after running the project. I believe they were referring to the unfortunate execution of `rm -rf /`.

I'm glad you enjoyed the LEEME.md! More projects will be added to it, provided that I survive the current _cuatri_.

Cheers, your Google, Guido
